"""add_account_name_and_currency

Revision ID: bc135f4487c1
Revises: d6cabea1d845
Create Date: 2025-04-09 15:08:49.891867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc135f4487c1'
down_revision: Union[str, None] = 'd6cabea1d845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_name', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('currency', sa.String(length=255), nullable=True))
    
    # Add default values for existing rows
    op.execute("UPDATE accounts SET account_name = 'Default Account', currency = 'USD'")
    
    # Make columns non-nullable after setting defaults
    op.alter_column('accounts', 'account_name', nullable=False)
    op.alter_column('accounts', 'currency', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'currency')
    op.drop_column('accounts', 'account_name')
    # ### end Alembic commands ###
